<div>
    <button>Oui</button>
    <button>Oui</button>
    <button>Oui</button>
    <button>Oui</button>
    <button>Oui</button>
    <button>Oui</button>
    <button>Oui</button>
    <button>Oui</button>
    <button>Oui</button>
    <button>Oui</button>
</div>